### ISSUE TITLE
why do you use Vertx

### ISSUE THREAD

**Issue by HoangNgo88** [scx567888/scx-ext#233]
Hi, Why do you use Vertx, are you using reactive programming, why dont you use Webflux in Spring. What is the difference between Vertx and Webflux when talking about Reactive Programming

**Comment by scx567888** [comment]
Vertx and Spring WebFlux are not the same thing, but if you have to compare them, Vertx is more simple and flexible.

As for Rx, I don't have much preference. Although it is more suitable for event-driven scenarios (such as UI), in most cases, using Rx is a bad experience.

What we should really expect is that Rx can simply transform with traditional programming models , Just like the "async" and "await" in other programming languages.

Fortunately, JEP 436: provides the possibility for all this.

**Comment by scx567888** [comment]
If you dont have other questions, I will close this issue
